version: "3.9"
services:
  postgres:
    image: "postgres"
    env_file:
      - database.env
    container_name: "postgres"
    ports:
      - "5432:5432"
  server:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    links:
      - postgres
